import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import Header from "./components/header/page";

export const metadata: Metadata = {
  title: "Maatwerk veranda kopen bij Gardenluxveranda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;300;400;500;700;900&family=Roboto+Mono:wght@100;300;400;500;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="antialiased w-full">
      <Header />
        {children}
      </body>
    </html>
  );
}
